# Generated by Django 4.2.15 on 2024-10-15 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("image", versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to="images/articles/categories")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Category",
                "verbose_name_plural": "Article Categories",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("pen_name", models.CharField(max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="images/articles/authors")),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="author_user", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Article Author",
                "verbose_name_plural": "Article Authors",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("title", models.CharField(max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("location", models.CharField(blank=True, max_length=128, null=True)),
                ("display_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("image", versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to="images/aticles/posts")),
                ("content", tinymce.models.HTMLField(verbose_name="Post Body")),
                (
                    "comment_option",
                    models.CharField(
                        choices=[("allow", "Allow"), ("show", "Do not allow, show existing"), ("hide", "Do not allow, hide existing")], default="allow", max_length=128
                    ),
                ),
                ("author", models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="post_author", to="articles.author")),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="post_category", to="articles.articlecategory"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Post",
                "verbose_name_plural": "Article Posts",
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("question", models.CharField(max_length=128)),
                ("answer", tinymce.models.HTMLField(verbose_name="FAQ Answer")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=128)),
                ("comment", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comment_post", to="articles.post")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
