# Generated by Django 4.2.15 on 2024-10-15 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("mobile", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=100, null=True)),
                ("parent_name", models.CharField(blank=True, max_length=100, null=True)),
                ("profession", models.CharField(blank=True, max_length=100, null=True)),
                ("educational_qualification", models.CharField(blank=True, max_length=100, null=True)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                ("designation", models.CharField(blank=True, max_length=100, null=True)),
                ("membership_year", models.CharField(choices=[("2019-2024", "2019-2024"), ("2024-2029", "2024-2029")], max_length=100)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("district", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.district")),
                ("state", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.state")),
                ("unit_ref", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.unit")),
                ("zone", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.zone")),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
