# Generated by Django 4.2.15 on 2024-10-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
