# Generated by Django 4.2.15 on 2024-10-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_member_whatsapp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="unit",
        ),
    ]
