# Generated by Django 4.2.15 on 2024-10-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_remove_member_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="unit_ref",
            new_name="unit",
        ),
    ]
