# Generated by Django 4.2.15 on 2024-10-15 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("taggit", "0004_alter_taggeditem_content_type_alter_taggeditem_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("is_verified", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=128)),
                ("logo", versatileimagefield.fields.VersatileImageField(upload_to="images/stream/logos")),
                ("cover", versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to="images/stream/covers")),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                (
                    "administrator",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="channel_administrator", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("image", versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to="images/stream/categories")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Category",
                "verbose_name_plural": "Video Categories",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("title", models.CharField(max_length=128)),
                ("video_id", models.CharField(max_length=11, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("cast", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="video_category", to="stream.videocategory"),
                ),
                (
                    "channel",
                    models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="video_channel", to="stream.channel"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="video_language", to="core.language"),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(blank=True, help_text="A comma-separated list of tags.", through="taggit.TaggedItem", to="taggit.Tag", verbose_name="Tags"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=128)),
                ("channel", models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="playlists", to="stream.channel")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("videos", models.ManyToManyField(to="stream.video")),
            ],
            options={
                "verbose_name": "Video Playlist",
                "verbose_name_plural": "Video Playlists",
            },
        ),
    ]
