BOOL_CHOICES = ((True, "Yes"), (False, "No"))

COUNTRY_CHOICES = (
    ("", "Country / Region"),
    ("af", "Afghanistan"),
    ("al", "Albanien"),
    ("dz", "Algerien"),
    ("ad", "Andorra"),
    ("ao", "Angola"),
    ("ag", "Antigua and Barbuda"),
    ("ar", "Argentinien"),
    ("am", "Armenien"),
    ("az", "Aserbaidschan"),
    ("au", "Australien"),
    ("bs", "Bahamas"),
    ("bh", "Bahrain"),
    ("bd", "Bangladesch"),
    ("bb", "Barbados"),
    ("by", "Belarus"),
    ("be", "Belgien"),
    ("bz", "Belize"),
    ("bj", "Benin"),
    ("bt", "Bhutan"),
    ("bo", "Bolivien"),
    ("ba", "Bosnien und Herzegowina"),
    ("bw", "Botswana"),
    ("br", "Brasilien"),
    ("bn", "Brunei Darussalam"),
    ("bg", "Bulgarien"),
    ("bf", "Burkina Faso"),
    ("bi", "Burundi"),
    ("cv", "Cape Verde"),
    ("cl", "Chile"),
    ("cn", "China"),
    ("km", "Comoros"),
    ("ck", "Cook Inseln"),
    ("cr", "Costa Rica"),
    ("ci", "Côte d'Ivoire"),
    ("cd", "Demokratische Republik Kongo"),
    ("de", "Deutschland"),
    ("dj", "Djibouti"),
    ("dm", "Dominica"),
    ("do", "Dominikanische Republik"),
    ("dk", "Dänemark"),
    ("ec", "Ecuador"),
    ("sv", "El Salvador"),
    ("er", "Eritrea"),
    ("ee", "Estland"),
    ("fj", "Fiji"),
    ("fi", "Finnland"),
    ("fr", "Frankreich"),
    ("ga", "Gabun"),
    ("gm", "Gambia"),
    ("ge", "Georgien"),
    ("gh", "Ghana"),
    ("gd", "Grenada"),
    ("gr", "Griechenland"),
    ("gt", "Guatemala"),
    ("gn", "Guinea"),
    ("gw", "Guinea-Bissau"),
    ("gy", "Guyana"),
    ("ht", "Haiti"),
    ("hn", "Honduras"),
    ("in", "Indien"),
    ("id", "Indonesien"),
    ("iq", "Irak"),
    ("ir", "Iran"),
    ("ie", "Irland"),
    ("is", "Island"),
    ("il", "Israel"),
    ("it", "Italien"),
    ("jm", "Jamaica"),
    ("jp", "Japan"),
    ("jo", "Jordanien"),
    ("kh", "Kambodscha"),
    ("cm", "Kamerun"),
    ("ca", "Kanada"),
    ("kz", "Kasachstan"),
    ("qa", "Katar"),
    ("ke", "Kenia"),
    ("kg", "Kirgisien"),
    ("ki", "Kiribati"),
    ("co", "Kolumbien"),
    ("kr", "Korea"),
    ("xk", "Kosovo"),
    ("hr", "Kroatien"),
    ("cu", "Kuba"),
    ("kw", "Kuwait"),
    ("la", "Laos"),
    ("ls", "Lesotho"),
    ("lv", "Lettland"),
    ("lb", "Libanon"),
    ("lr", "Liberia"),
    ("ly", "Libyen"),
    ("li", "Liechtenstein"),
    ("lt", "Litauen"),
    ("lu", "Luxemburg"),
    ("mg", "Madagaskar"),
    ("mw", "Malawi"),
    ("my", "Malaysia"),
    ("mv", "Malediven"),
    ("ml", "Mali"),
    ("mt", "Malta"),
    ("ma", "Marokko"),
    ("mh", "Marshall Inseln"),
    ("mr", "Mauretanien"),
    ("mu", "Mauritius"),
    ("mx", "Mexiko"),
    ("fm", "Mikronesien"),
    ("mc", "Monaco"),
    ("mn", "Mongolei"),
    ("me", "Montenegro"),
    ("mz", "Mosambik"),
    ("mm", "Myanmar"),
    ("na", "Namibia"),
    ("nr", "Nauru"),
    ("np", "Nepal"),
    ("nz", "Neuseeland"),
    ("ni", "Nicaragua"),
    ("nl", "Niederlande"),
    ("ne", "Niger"),
    ("ng", "Nigeria"),
    ("nu", "Niue"),
    ("kp", "Nord-Korea"),
    ("mk", "Nordmazedonien"),
    ("no", "Norwegen"),
    ("om", "Oman"),
    ("tl", "Ost Timor"),
    ("pk", "Pakistan"),
    ("pw", "Palau"),
    ("ps", "Palästinensische Gebiete"),
    ("pa", "Panama"),
    ("pg", "Papua Neuguinea"),
    ("py", "Paraguay"),
    ("pe", "Peru"),
    ("ph", "Philippinen"),
    ("pl", "Polen"),
    ("pt", "Portugal"),
    ("pr", "Puerto Rico"),
    ("cg", "Republik Kongo"),
    ("md", "Republik Moldau"),
    ("cf", "Republik Zentralafrika"),
    ("rw", "Ruanda"),
    ("ro", "Rumänien"),
    ("ru", "Russland"),
    ("lc", "Saint Lucia"),
    ("vc", "Saint Vincent und die Grenadinen"),
    ("zm", "Sambia"),
    ("ws", "Samoa"),
    ("sm", "San Marino"),
    ("sa", "Saudi-Arabien"),
    ("se", "Schweden"),
    ("ch", "Schweiz"),
    ("sn", "Senegal"),
    ("rs", "Serbien"),
    ("sc", "Seychellen"),
    ("sl", "Sierra Leone"),
    ("sg", "Singapur"),
    ("sk", "Slowakei"),
    ("si", "Slowenien"),
    ("sb", "Solomon Islands"),
    ("so", "Somalia"),
    ("es", "Spanien"),
    ("lk", "Sri Lanka"),
    ("kn", "St. Kitts und Nevis"),
    ("sd", "Sudan"),
    ("sr", "Surinam"),
    ("sz", "Swasiland"),
    ("sy", "Syrien"),
    ("st", "São Tomé und Principe"),
    ("za", "Südafrika"),
    ("ss", "Südsudan"),
    ("tw", "Taiwan"),
    ("tw", "Taiwan (Region)"),
    ("tj", "Tajikistan"),
    ("tz", "Tansania"),
    ("th", "Thailand"),
    ("tg", "Togo"),
    ("to", "Tonga"),
    ("tt", "Trinidad und Tobago"),
    ("td", "Tschad"),
    ("cz", "Tschechien"),
    ("tn", "Tunesien"),
    ("tm", "Turkmenistan"),
    ("tv", "Tuvalu"),
    ("tr", "Türkei"),
    ("us", "USA"),
    ("ug", "Uganda"),
    ("ua", "Ukraine"),
    ("hu", "Ungarn"),
    ("uy", "Uruguay"),
    ("uz", "Usbekistan"),
    ("vu", "Vanuatu"),
    ("va", "Vatikanstadt"),
    ("ve", "Venezuela"),
    ("ae", "Vereinigte Arabische Emirate"),
    ("gb", "Vereinigtes Königreich"),
    ("vn", "Vietnam"),
    ("ye", "Yemen"),
    ("cy", "Zypern"),
    ("eg", "Ägypten"),
    ("gq", "Äquatorial Guinea"),
    ("et", "Äthiopien"),
    ("at", "Österreich"),
)
