# Generated by Django 4.2.15 on 2024-10-15 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Administration",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("code", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZoneCommittee",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                (
                    "committee",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="zone_committee_committee", to="committees.administration"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executive_members",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="zone_committee_executive_members", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "joint_secretaries",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="zone_committee_joint_secretaries", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "president",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zone_committee_president",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secretariat_members",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="zone_committee_secretariat_members", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "secretary",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zone_committee_secretary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treasurer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zone_committee_treasurer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vice_presidents",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="zone_committee_vice_presidents", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True, limit_choices_to={"is_active": True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="zone_committee_zone", to="core.zone"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnitCommittee",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                (
                    "committee",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="unit_committee_committee", to="committees.administration"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executive_members",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="unit_committee_executive_members", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "joint_secretaries",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="unit_committee_joint_secretaries", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "president",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_committee_president",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secretariat_members",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="unit_committee_secretariat_members", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "secretary",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_committee_secretary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treasurer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit_committee_treasurer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True, limit_choices_to={"is_active": True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="unit_committee_unit", to="core.unit"
                    ),
                ),
                (
                    "vice_presidents",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="unit_committee_vice_presidents", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("level", models.CharField(choices=[("state", "State"), ("district", "District"), ("zone", "Zone"), ("unit", "Unit")], max_length=128)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="type_organization", to="committees.organization"
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Type",
                "verbose_name_plural": "Committee Types",
                "ordering": ("organization",),
            },
        ),
        migrations.CreateModel(
            name="StateCommittee",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                (
                    "committee",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_committee_administration",
                        to="committees.administration",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executive_members",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="state_committee_executive_members", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "joint_secretaries",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="state_committee_joint_secretaries", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "president",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_committee_president",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secretariat_members",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="state_committee_secretariat_members", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "secretary",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_committee_secretary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_committee_state",
                        to="core.state",
                    ),
                ),
                (
                    "treasurer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_committee_treasurer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vice_presidents",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="state_committee_vice_presidents", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictCommittee",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                (
                    "committee",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="district_committee_committee",
                        to="committees.administration",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="district_committee_district",
                        to="core.district",
                    ),
                ),
                (
                    "executive_members",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="district_committee_executive_members", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "joint_secretaries",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="district_committee_joint_secretaries", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "president",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="district_committee_president",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secretariat_members",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="district_committee_secretariat_members", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "secretary",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="district_committee_secretary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treasurer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="district_committee_treasurer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vice_presidents",
                    models.ManyToManyField(blank=True, limit_choices_to={"is_active": True}, related_name="district_committee_vice_presidents", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="administration",
            name="type",
            field=models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="administration_type", to="committees.type"),
        ),
        migrations.AddField(
            model_name="administration",
            name="year",
            field=models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="administration_year", to="core.year"),
        ),
    ]
