# Generated by Django 4.2.15 on 2024-10-15 13:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=128)),
                ("location", models.CharField(max_length=128)),
                ("mobile", models.CharField(max_length=128)),
                ("whatsapp", models.CharField(blank=True, max_length=128, null=True)),
                ("address", models.TextField(blank=True, null=True, verbose_name="Address")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agency",
                "verbose_name_plural": "Agencies",
            },
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("sl_no", models.PositiveIntegerField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(blank=True, max_length=128, null=True)),
                ("address", models.TextField(blank=True, null=True, verbose_name="Address")),
                ("mobile", models.CharField(max_length=128)),
                ("whatsapp", models.CharField(blank=True, max_length=128, null=True)),
                ("passport_number", models.CharField(max_length=128)),
                ("passport_issue", models.DateField(verbose_name="Passport Issue Date")),
                ("passport_expiry", models.DateField(verbose_name="Passport Expiry Date")),
                ("place_of_issue", models.CharField(max_length=128)),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                ("gender", models.CharField(choices=[("Male", "Male"), ("Female", "Female")], max_length=128)),
                ("discount", models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("mahram_name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "mahram_relation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WIFE", "Wife"),
                            ("FATHER_S_WIFE", "Father’s wife"),
                            ("MOTHER", "Mother"),
                            ("DAUGHTER", "Daughter"),
                            ("SISTER", "Sister"),
                            ("AUNT", "Aunt"),
                            ("NIECE", "Niece"),
                            ("FOSTER_MOTHER", "Foster Mother"),
                            ("FOSTER_SISTER", "Foster Sister"),
                            ("MOTHER_IN_LAW", "Mother-in-law"),
                            ("DAUGHTER_IN_LAW", "Daughter-in-law"),
                            ("HUSBAND", "Husband"),
                            ("STEP_FATHER", "Step father"),
                            ("FATHER", "Father"),
                            ("SON", "Son"),
                            ("BROTHER", "Brother"),
                            ("UNCLE", "Uncle"),
                            ("NEPHEW", "Nephew"),
                            ("FOSTER_SON", "Foster son"),
                            ("FOSTER_BROTHER", "Foster Brother"),
                            ("FATHER_IN_LAW", "Father-in-law"),
                            ("SON_IN_LAW", "Son-in-law"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Required photo size: 4.5cm in height and 3.5cm in width, Colored picture, Must not be older than 6 months, Background: white.",
                        upload_to="images/umrah/applicants",
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True, limit_choices_to={"is_active": True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="applicant_agency", to="umrah.agency"
                    ),
                ),
            ],
            options={
                "verbose_name": "Umrah Applicant",
                "verbose_name_plural": "Umrah Applicants",
                "ordering": ("sl_no", "batch"),
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("serial_no", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ("residence", models.TextField(blank=True, null=True, verbose_name="Residence in Makkah")),
                ("slug", models.SlugField(unique=True)),
                (
                    "color",
                    models.CharField(
                        choices=[("RED", "RED"), ("BLUE", "BLUE"), ("GREEN", "GREEN"), ("LIGHTBLUE", "LIGHTBLUE"), ("MAGENTA", "MAGENTA"), ("PINK", "PINK"), ("YELLOW", "YELLOW")],
                        default="RED",
                        max_length=128,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("year", models.IntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Umrah Batch",
                "verbose_name_plural": "Umrah Batches",
                "ordering": ("serial_no",),
            },
        ),
        migrations.CreateModel(
            name="PaymentPurpose",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Purpose",
                "verbose_name_plural": "Payment Purposes",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("voucher_number", models.CharField(max_length=128, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("date", models.DateField(verbose_name="Date of Payment")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notes")),
                ("mode", models.CharField(choices=[("CASH", "CASH"), ("BANK", "BANK")], default="CASH", max_length=128)),
                ("batch", models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="voucher_batch", to="umrah.batch")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="voucher_purpose", to="umrah.paymentpurpose"),
                ),
            ],
            options={
                "verbose_name": "Voucher",
                "verbose_name_plural": "Vouchers",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UmrahPayment",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("reciept_number", models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("roundoff", models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ("date", models.DateField(verbose_name="Date of Payment")),
                ("mode", models.CharField(choices=[("CASH", "CASH"), ("BANK", "BANK")], default="CASH", max_length=128)),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notes")),
                (
                    "applicant",
                    models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="payment_applicant", to="umrah.applicant"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="applicant",
            name="batch",
            field=models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="applicant_batch", to="umrah.batch"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="creator",
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_creator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="applicant",
            unique_together={("batch", "passport_number")},
        ),
    ]
