# Generated by Django 4.2.15 on 2024-10-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umrah", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="mobile",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="passport_expiry",
            field=models.DateField(blank=True, null=True, verbose_name="Passport Expiry Date"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="passport_issue",
            field=models.DateField(blank=True, null=True, verbose_name="Passport Issue Date"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="passport_number",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="place_of_issue",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
