# Generated by Django 4.2.15 on 2025-03-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("umrah", "0002_alter_applicant_dob_alter_applicant_mobile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="agency",
            field=models.ForeignKey(
                blank=True, limit_choices_to={"is_active": True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="voucher_agency", to="umrah.agency"
            ),
        ),
    ]
