# Generated by Django 4.2.15 on 2025-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umrah", "0003_voucher_agency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="voucher_number",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
