# Generated by Django 4.2.15 on 2025-06-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umrah", "0004_alter_voucher_voucher_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voucher",
            options={"ordering": ("-voucher_number",), "verbose_name": "Voucher", "verbose_name_plural": "Vouchers"},
        ),
        migrations.AlterField(
            model_name="umrahpayment",
            name="mode",
            field=models.CharField(
                choices=[("CASH", "CASH"), ("BANK", "BANK TRANSFER"), ("CHEQUE", "CHEQUE PAYMENT"), ("UPI", "UPI PAYMENT"), ("ONLINE", "ONLINE TRANSFER")],
                default="CASH",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="mode",
            field=models.CharField(
                choices=[("CASH", "CASH"), ("BANK", "BANK TRANSFER"), ("CHEQUE", "CHEQUE PAYMENT"), ("UPI", "UPI PAYMENT"), ("ONLINE", "ONLINE TRANSFER")],
                default="CASH",
                max_length=128,
            ),
        ),
    ]
