# Generated by Django 5.2.4 on 2025-07-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umrah', '0005_alter_voucher_options_alter_umrahpayment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahpayment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
