# Generated by Django 4.2.9 on 2025-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umrah", "0006_umrahpayment_is_archived_voucher_is_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="color",
            field=models.CharField(choices=[("RED", "RED"), ("BLUE", "BLUE"), ("GREEN", "GREEN"), ("PINK", "PINK"), ("YELLOW", "YELLOW")], default="RED", max_length=128),
        ),
    ]
