# Generated by Django 4.2.15 on 2024-10-15 13:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("pen_name", models.CharField(max_length=128)),
                ("about", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="publisher_user", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MagazineCategory",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("image", versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to="images/publications/categories")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Magazine Category",
                "verbose_name_plural": "Magazine Categories",
            },
        ),
        migrations.CreateModel(
            name="Magazine",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("name", models.CharField(max_length=128, verbose_name="Magazine Name")),
                ("about", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True, verbose_name="Website Address")),
                ("text_direction", models.CharField(choices=[("rtl", "Right to Left"), ("ltl", "Left to Right")], max_length=128)),
                (
                    "category",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="magazine_category", to="publications.magazinecategory"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="magazine_country",
                        to="core.country",
                        verbose_name="Publishing Country",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="magazine_language",
                        to="core.language",
                        verbose_name="Magazine Language",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("id", models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(choices=[(True, "Yes"), (False, "No")], default=True, verbose_name="Mark as Active")),
                ("title", models.CharField(max_length=128, verbose_name="Book Title")),
                ("description", models.TextField(blank=True, null=True)),
                ("number", models.PositiveIntegerField(verbose_name="Issue Number")),
                ("price", models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("cover_image", versatileimagefield.fields.VersatileImageField(upload_to="images/publications/books", verbose_name="Cover Image")),
                ("date", models.DateField(verbose_name="Publishing Date")),
                ("file", models.FileField(upload_to="books")),
                ("is_free", models.BooleanField(default=False)),
                (
                    "is_special_issue",
                    models.BooleanField(default=False, help_text="Special issue will not be come under subscription. User has to purchase single issue to read it"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "magazine",
                    models.ForeignKey(limit_choices_to={"is_active": True}, on_delete=django.db.models.deletion.PROTECT, related_name="issue_magazine", to="publications.magazine"),
                ),
            ],
            options={
                "verbose_name": "Magazine Issue",
                "verbose_name_plural": "Magazine Issues",
                "ordering": ("-number", "-date"),
            },
        ),
    ]
